// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBSMsu1wm5rhxC6GWREI-lAZmv6V5soAFs',
    appId: '1:1008186092510:web:c247cfaa8b104a60480b4f',
    messagingSenderId: '1008186092510',
    projectId: 'storyo-48051',
    authDomain: 'storyo-48051.firebaseapp.com',
    storageBucket: 'storyo-48051.firebasestorage.app',
    measurementId: 'G-0RQHY92T9D',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA8_kgUwkMr-XwO5ZNg2NRTGVW0y-Pkp9A',
    appId: '1:1008186092510:android:9981af204f85e406480b4f',
    messagingSenderId: '1008186092510',
    projectId: 'storyo-48051',
    storageBucket: 'storyo-48051.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDa5GEddvU1Iajoae8uOqvcC32i_z4B70E',
    appId: '1:1008186092510:ios:66f69e5dabb6eaf9480b4f',
    messagingSenderId: '1008186092510',
    projectId: 'storyo-48051',
    storageBucket: 'storyo-48051.firebasestorage.app',
    iosBundleId: 'com.example.storyo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDa5GEddvU1Iajoae8uOqvcC32i_z4B70E',
    appId: '1:1008186092510:ios:66f69e5dabb6eaf9480b4f',
    messagingSenderId: '1008186092510',
    projectId: 'storyo-48051',
    storageBucket: 'storyo-48051.firebasestorage.app',
    iosBundleId: 'com.example.storyo',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBSMsu1wm5rhxC6GWREI-lAZmv6V5soAFs',
    appId: '1:1008186092510:web:b0d4858c6ea2ad54480b4f',
    messagingSenderId: '1008186092510',
    projectId: 'storyo-48051',
    authDomain: 'storyo-48051.firebaseapp.com',
    storageBucket: 'storyo-48051.firebasestorage.app',
    measurementId: 'G-KYLVN0RWHL',
  );
}
